name: smip-conda
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.*
  - scipy=1.6.*
  - pandas=1.2.*
  - dash=1.20.*
  - dash-bootstrap-components=0.12.*
  - pyjwt=2.1.*
  - requests=2.26.*
  - requests-futures=1.0.*
  - matplotlib=3.4.*
  - nidaqmx-python=0.5.*
  - autopep8
  - pylint
